### ISSUE TITLE
Add method to check data ready flag

### ISSUE THREAD

**Issue by jmfloyd** [barbudor/CircuitPython_INA3221#3]
I added this method to my class that uses your libray using self.ina3221 as the instance of your library.  But this could be included in your library.

This aids waiting for available data.

`
    def ina3221_CRF(self):
         # get conv_ready_flag
         regvalue = self.ina3221.read(ina.C_REG_MASK_ENABLE)
         value = (regvalue & ina.C_CONV_READY_FLAG)
         return (value==1)
`

**Comment by barbudor** [comment]
@jmfloyd 
I understand you using the full version ?
By default, both versions initialize the INA in continuous mode, so there should always be values ready for reading.
Have you changed this behavior ?
If so, how did you do that ? Would a method for updating the config register convenient to add too ?
I can add that to the full version but would prefer to keep the lite version as lite as possible as SAMD21 doesn't have much memory.

**Comment by jmfloyd** [comment]
I understood that the registers are always available to read, but the ready flag indicates that a new set of values are available.  Else you may be reading previous values.  it seems to work well.  YesxI use continuous mode as well. The docs, I thought, says that the ready flag is reset after reading.  Sorry dont havebthe docs on hand.Cheers JohnOn Jan 4, 2021 8:07 PM, Barbudor <notifications@github.com> wrote:
@jmfloyd
I understand you using the full version ?
By default, both versions initialize the INA in continuous mode, so there should always be values ready for reading.
Have you changed this behavior ?
If so, how did you do that ? Would a method for updating the config register convenient to add too ?
I can add that to the full version but would prefer to keep the lite version as lite as possible as SAMD21 doesn't have much memory.

**Comment by barbudor** [comment]
Closed by https://github.com/barbudor/CircuitPython_INA3221/commit/cf73188006d7894aa72e90425ba13670918143f9
Released as v1.2 for automatic integration into Circuit Python Community Bundle
