### ISSUE TITLE
Question: how to install on Raspberry Pi

### ISSUE THREAD

**Issue by kkellner** [barbudor/CircuitPython_INA3221#5]
I know the readme says its not available via PyPI.  How would I go about installing this library on a Raspberry Pi?  Can I download the release zip and use pip3 to install somehow?

I tried the following but it didn't work so must be a bit more involved to install.

```
$ sudo pip3 install barbudor_ina3221.precompiled.binaries.zip
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing ./barbudor_ina3221.precompiled.binaries.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-rn99zd6q/setup.py'
```

**Comment by barbudor** [comment]
Hi @kkellner 
The easiest way is to extract from the zip the folder `barbudor_ina3221\` and to copy/move it into your current directory.
```
-- your project dir\
        +-- your own files.py
        +-- barbudor_ina3221\
                   +-- __init__.py
                   +-- lite.py
                   +-- full.py
```
And then you can use it exactly as described

I never generated a PiPy package right now but if you know a simple library similar to this one that supports it, let me know and I can look at it and implement it over the week-end.

Best regards

**Comment by kkellner** [comment]
Thanks, I'll do it that way and embed it into my project.

An example Pypi that comes to mind in the Alexa python library.  Its on gitlab but that shouldn't make a difference.  Hopefully it has the example bits you need.

Lib on Pypi: https://pypi.org/project/alexapy/
Code: https://gitlab.com/keatontaylor/alexapy

**Comment by barbudor** [comment]
I've done the PyPi package 
I've tested that I can install it but not with the hardware
Can you check ?
`pip install [--user] barbudor-circuitpython-ina3221`

Let me know
Cheers

**Comment by kkellner** [comment]
I will not be able to test the library for a few days while I await the delivery of an ina3221 device, but the install appears to have worked:

```
$ sudo pip3 install  barbudor-circuitpython-ina3221
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting barbudor-circuitpython-ina3221
  Downloading https://www.piwheels.org/simple/barbudor-circuitpython-ina3221/barbudor_circuitpython_ina3221-1.2.0-py3-none-any.whl
Requirement already satisfied: adafruit-circuitpython-busdevice in /usr/local/lib/python3.7/dist-packages (from barbudor-circuitpython-ina3221) (5.0.1)
Requirement already satisfied: Adafruit-Blinka in /usr/local/lib/python3.7/dist-packages (from barbudor-circuitpython-ina3221) (5.9.2)
Requirement already satisfied: rpi-ws281x>=4.0.0 in /usr/local/lib/python3.7/dist-packages (from Adafruit-Blinka->barbudor-circuitpython-ina3221) (4.2.5)
Requirement already satisfied: pyftdi>=0.40.0 in /usr/local/lib/python3.7/dist-packages (from Adafruit-Blinka->barbudor-circuitpython-ina3221) (0.52.0)
Requirement already satisfied: Adafruit-PureIO>=1.1.7 in /usr/local/lib/python3.7/dist-packages (from Adafruit-Blinka->barbudor-circuitpython-ina3221) (1.1.8)
Requirement already satisfied: sysv-ipc in /usr/local/lib/python3.7/dist-packages (from Adafruit-Blinka->barbudor-circuitpython-ina3221) (1.0.1)
Requirement already satisfied: RPi.GPIO in /usr/lib/python3/dist-packages (from Adafruit-Blinka->barbudor-circuitpython-ina3221) (0.7.0)
Requirement already satisfied: Adafruit-PlatformDetect>=2.18.1 in /usr/local/lib/python3.7/dist-packages (from Adafruit-Blinka->barbudor-circuitpython-ina3221) (2.23.0)
Requirement already satisfied: pyusb>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from pyftdi>=0.40.0->Adafruit-Blinka->barbudor-circuitpython-ina3221) (1.1.0)
Requirement already satisfied: pyserial>=3.0 in /usr/local/lib/python3.7/dist-packages (from pyftdi>=0.40.0->Adafruit-Blinka->barbudor-circuitpython-ina3221) (3.5)
Installing collected packages: barbudor-circuitpython-ina3221
Successfully installed barbudor-circuitpython-ina3221-1.2.0
```

**Comment by barbudor** [comment]
Cool
Kindly keep me posted
Cheers

**Comment by kkellner** [comment]
I believe the pip install worked however I'm getting the following error
when trying to run the ina3221_simpletest.py code (using python3)

```
 $ sudo python3 ina3221_simpletest.py
full API sample: improve accuracy
Traceback (most recent call last):
  File "ina3221_simpletest.py", line 32, in <module>
    C_MODE_SHUNT_AND_BUS_CONTINOUS)
  File "/usr/local/lib/python3.7/dist-packages/barbudor_ina3221/full.py",
line 185, in update
    regvalue = self.read(reg)
  File "/usr/local/lib/python3.7/dist-packages/barbudor_ina3221/full.py",
line 178, in read
    i2c.write(buf, end=1, stop=False)
TypeError: write() got an unexpected keyword argument 'stop'
```

The device is visible from the I2C bus:
```
$ sudo i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: 40 -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
```

This is the board I'm using:  https://www.amazon.com/gp/product/B07X524KSK

Thoughts?

**Comment by kkellner** [comment]
I believe the pip install worked however I'm getting the following error
when trying to run the ina3221_simpletest.py code
```
$ sudo python3 ina3221_simpletest.py
full API sample: improve accuracy
Traceback (most recent call last):
  File "ina3221_simpletest.py", line 32, in <module>
    C_MODE_SHUNT_AND_BUS_CONTINOUS)
  File "/usr/local/lib/python3.7/dist-packages/barbudor_ina3221/full.py",
line 185, in update
    regvalue = self.read(reg)
  File "/usr/local/lib/python3.7/dist-packages/barbudor_ina3221/full.py",
line 178, in read
    i2c.write(buf, end=1, stop=False)
TypeError: write() got an unexpected keyword argument 'stop'
```

The device is visible from the I2C bus:
```
$ sudo i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: 40 -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
```

This is the board I'm using:  https://www.amazon.com/gp/product/B07X524KSK

Thoughts?

**Comment by kkellner** [comment]
I'm not seeing a `stop` param to the i2c write method.  Do I have the wrong version of the adafruit lab?


i2c write method ref:
https://circuitpython.readthedocs.io/projects/busdevice/en/latest/api.html#adafruit_bus_device.i2c_device.I2CDevice.write

Call from this lib:
https://github.com/barbudor/CircuitPython_INA3221/blob/master/barbudor_ina3221/full.py#L178

**Comment by barbudor** [comment]
I wrote this library in time of CircuitPython v3.0 and never re-used it since, and apparently no-one else before youself.
The `stop` parameter was here until 4.3.2 :  https://circuitpython.readthedocs.io/projects/busdevice/en/4.3.2/api.html#adafruit_bus_device.i2c_device.I2CDevice.write

Apparently this call sequence :
```
            i2c.write(buf, end=1, stop=False)
            i2c.readinto(buf, start=1)
```
should be replaced with
```
            i2c.write_then_readinto(buf, buf, out_start=1, in_end=1)
```
However, it's late now here (I'm @GMT+1) so I'll have a look tomorrow but you may try it yourself by copying the code into your project and editing the occurrence of the call.
Sorry for the inconvenience.

**Comment by kkellner** [comment]
I tried the following but it didn't work.  The values come back but are incorrect.
```
            i2c.write_then_readinto(buf, buf, out_start=1, in_end=1)
```

I then tried this and all is working:
```
            i2c.write(buf, end=1)
```

So it seems just removing the `stop=False` did the trick.  I've been running for a few hours and the values seem accurate.

**Comment by barbudor** [comment]
So I just mis-understood in and out
The correct syntax is
```
i2c.write_then_readinto(buf, buf, out_end=1, in_start=1)
```

I will change for this in the lib and publish a new release on PyPi
I'll let you know

**Comment by barbudor** [comment]
Lib v2.0.0 published on PyPi
Thanks for pointing the problems and helping testing.

**Comment by kkellner** [comment]
Confirmed v2.0.0 is working on Raspberry Pi4b + Python3.   Thank you so much for updating the library.  I was just happy to find a CircuitPython compatible library for the INA3221.
